### ISSUE TITLE
Request add switch to disable debug output of request/response

### ISSUE THREAD

**Issue by jenningsloy318** [pepabo/go-netapp#30]
Hi,
for Client `NewRequest` and `Do` function, they are always print the whole request and response, 
if it is possible to have a switch to disable debug output ?

I am implementing a monitor export for netapp storage, since prometheus will call this agent quit frequent, so a lot of output printed.

**Comment by jenningsloy318** [comment]
Hi,
I created a pull request to add this feather, Can you please reiview it ? 
#31

**Comment by pyama86** [comment]
Hi! Good morning!
Japan time is now Monday morning. I'll review it from now.
